services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"  # Ajuste aquí, eliminando el guión extra
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
